### ISSUE TITLE
SwapRedAndBlue

### ISSUE THREAD

**Issue by kcimit** [sdcb/Sdcb.LibRaw#1]
Thank you for a good implémentation of wrapper.
I wonder what are the scenarios requiring swapping red and blue components?
Tried to search in libraw.org cannot find any mentioning why it is needed.

**Comment by sdcb** [comment]
Thank you for using my open source project, because if I don't swap red and blue, the color seems strange in my Bitmap, maybe because bitmap is using RGB24 however libraw generates BGR24.

**Comment by sdcb** [comment]
There is more background story, there is a `bgr` flag in libraw source code:
https://github.com/LibRaw/LibRaw/blob/0e105f9f8c159c6c7d8e9f6bb66ae54a0e58bac5/src/postprocessing/mem_image.cpp#L214-L244

However this flag is never been used and always be `0`: 
https://github.com/LibRaw/LibRaw/blob/0e105f9f8c159c6c7d8e9f6bb66ae54a0e58bac5/src/postprocessing/mem_image.cpp#L259-L283

**Comment by kcimit** [comment]
So it looks like it platform specific - not related to input raw file itself.
I'm using WindowsWPF net7.0 and it doesn't need swapping:

unsafe
            {
                fixed (void* data = rgbImage.GetData<byte>())
                {
                    var dpiX = 96d;
                    var dpiY = 96d;
                    var pixelFormat = System.Windows.Media.PixelFormats.Rgb24; 

                    var src = BitmapSource.Create(rgbImage.Width, rgbImage.Height, dpiX, dpiY,
                        pixelFormat, null, (IntPtr)data, rgbImage.Width*rgbImage.Height*3, rgbImage.Width * 3);

                    return src;
                }
            }

**Comment by sdcb** [comment]
hmm, interesting, let me check, have you also tested .net 6, is it .net 6 need swap while .net 7 don't need?

**Comment by sdcb** [comment]
@kcimit I confirmed, only WPF's `BitmapSource` don't need swap red and blue, OpencvSharp4 and Bitmap all need swap.
