### ISSUE TITLE
为什么解完的Raw这么黄？

### ISSUE THREAD

**Issue by 3egirlsdream** [sdcb/Sdcb.LibRaw#2]
- 一种是先解RAW然后转为Bitmap再使用SkiaSharp读取，保存为jpg
- 另一种是根据你提供的r.SaveRawImage(@"C:\test\test.tiff");
- 两种的很黄，是我操作的问题吗
- ![imag](https://cdn.thankful.top/SdcbLibRaw.jpg)

**Comment by sdcb** [comment]
见这篇文章：
https://www.cnblogs.com/sdflysha/p/20230801-sdcb-libraw-intro.html

可以应用机内白平衡解决问题：    
```csharp
c.UseCameraWb = true; // 使用机内白平衡，false则会由UserMultipliers控制白平衡
```

**Comment by 3egirlsdream** [comment]
是的，启用白平衡后，解决了，还想问下一下有支持MAUI 的计划吗？

**Comment by sdcb** [comment]
MAUI天生是没问题的，只需要自行编译对应Android或iOS平台的libraw，用于替换Sdcb.LibRaw.runtime.***，这个包其实没什么魔法，就是libraw官网C源代码编译即可。

**Comment by 3egirlsdream** [comment]
> MAUI天生是没问题的，只需要自行编译对应Android或iOS平台的libraw，用于替换Sdcb.LibRaw.runtime.***，这个包其实没什么魔法，就是libraw官网C源代码编译即可。

感谢
